import Foundation

runNamingChecks()
runStylerChecks()
runFormattingChecks()
runJSONFormatterChecks()
runHTMLChecks()
runExportPageChecks()
runTabChecks()
runTabPinChecks()
runLineEditingChecks()
runSummaryChecks()
runFuzzyMatchChecks()
runLanguageChecks()
runHighlighterChecks()
runFoldingChecks()
runFoldingEdgeChecks()
runOutlineChecks()
await runStoreChecks()
runRenameChecks()
await runLockChecks()
await runOrderAndFileChecks()
await runFileSafetyChecks()
await runSearchChecks()
await runPinChecks()
runCacheCompatibilityChecks()
runGroupChecks()
runSidebarReorderChecks()
runLineIndexChecks()

print("\(passes) passed, \(failures) failed")
exit(failures == 0 ? 0 : 1)
