import Foundation
import HardydoNotesCore

func runTabChecks() {
    let a = UUID(), b = UUID(), c = UUID(), d = UUID()
    var tabs = TabList()
    tabs.open(a, keep: false)
    checkEqual(tabs.ids, [a], "first click opens a preview tab")
    checkEqual(tabs.transient, a, "single click tab is a preview")
    tabs.open(b, keep: false)
    check(tabs.ids == [b] && tabs.active == b, "next single click replaces the preview tab")
    tabs.keep(b)
    tabs.open(c, keep: false)
    check(tabs.ids == [b, c] && tabs.transient == c, "a kept tab stays when another note is clicked")
    tabs.open(b, keep: false)
    check(tabs.ids == [b, c] && tabs.active == b && tabs.transient == c, "clicking an open note reuses its tab")
    tabs.open(d, keep: true)
    checkEqual(tabs.ids, [b, d, c], "a kept tab opens right of the active one")
    check(tabs.transient == c, "opening a kept tab leaves the preview alone")
    tabs.open(c, keep: true)
    check(tabs.transient == nil && tabs.active == c, "keeping the preview tab makes it permanent")

    tabs.activate(d)
    tabs.close(d)
    checkEqual(tabs.active, c, "closing the active tab moves to its right")
    tabs.close(c)
    checkEqual(tabs.active, b, "closing the last tab moves to its left")
    tabs.close(b)
    check(tabs.ids.isEmpty && tabs.active == nil, "closing every tab leaves nothing active")

    tabs = TabList(ids: [a, b, c, d], active: b)
    tabs.closeRight(of: a)
    check(tabs.ids == [a] && tabs.active == a, "closing tabs to the right moves off a closed active tab")
    tabs = TabList(ids: [a, b, c], active: c)
    tabs.closeOthers(b)
    check(tabs.ids == [b] && tabs.active == b, "close others keeps only that tab")

    tabs = TabList(ids: [a, b, c], active: a)
    tabs.cycle(by: -1)
    checkEqual(tabs.active, c, "previous tab wraps around")
    tabs.cycle(by: 1)
    checkEqual(tabs.active, a, "next tab wraps around")
    tabs.reorder([b, c, a])
    checkEqual(tabs.ids, [b, c, a], "a dragged tab lands where it was dropped")

    tabs = TabList(ids: [a, b, c], active: b)
    tabs.prune(keeping: [a, c])
    check(tabs.ids == [a, c] && tabs.active == c, "tabs of vanished notes close and the active tab moves on")
    checkEqual(TabList(ids: [a, b], active: d).active, a, "restored tabs fall back to the first tab")
}

func runTabPinChecks() {
    let a = UUID(), b = UUID(), c = UUID(), d = UUID()
    var tabs = TabList(ids: [a, b, c], active: a)
    tabs.pin(c)
    checkEqual(tabs.ids, [c, a, b], "a pinned tab moves to the front")
    check(tabs.isPinned(c) && !tabs.isPinned(a), "only the pinned tab reports pinned")
    tabs.open(d, keep: true)
    tabs.activate(c)
    tabs.open(UUID(), keep: true)
    check(tabs.ids.firstIndex(of: c) == 0 && tabs.pinnedCount == 1, "new tabs never open among pinned ones")

    tabs = TabList(ids: [a, b, c], active: b, pinned: [b])
    checkEqual(tabs.ids, [b, a, c], "restored pins come first")
    tabs.closeAll()
    checkEqual(tabs.ids, [b], "close all keeps pinned tabs")
    tabs = TabList(ids: [a, b, c, d], active: c, pinned: [a])
    tabs.closeOthers(c)
    checkEqual(tabs.ids, [a, c], "close others keeps pinned tabs")
    tabs = TabList(ids: [a, b, c], active: c, pinned: [a, b])
    tabs.closeRight(of: a)
    checkEqual(tabs.ids, [a, b], "close to the right keeps pinned tabs")
    check(!tabs.canCloseAll && !tabs.canCloseOthers(a) && !tabs.canCloseRight(of: a),
          "close commands are off when only pinned tabs are left")
    tabs.open(c, keep: true)
    check(tabs.canCloseOthers(a) && tabs.canCloseRight(of: a) && !tabs.canCloseRight(of: c),
          "close commands turn on while an unpinned tab can close")
    tabs.close(c)
    tabs.reorder([b, a])
    checkEqual(tabs.ids, [b, a], "pinned tabs reorder among themselves")
    tabs.unpin(b)
    check(tabs.ids == [a, b] && !tabs.isPinned(b), "an unpinned tab goes right after the pinned ones")

    tabs = TabList(ids: [a, b, c], active: a, pinned: [a])
    tabs.reorder([b, a, c])
    checkEqual(tabs.ids, [a, b, c], "a drag never moves a tab across the pinned boundary")
    tabs.reorder([a, b])
    checkEqual(tabs.ids, [a, b, c], "an order missing a tab is ignored")
    tabs.reorder([a, c, b])
    checkEqual(tabs.ids, [a, c, b], "unpinned tabs reorder after the pinned ones")

    tabs = TabList(ids: [a, b, c], active: b)
    tabs.close(b)
    tabs.close(c)
    checkEqual(tabs.reopen(existing: [a, b, c]), c, "reopen brings back the last closed tab")
    checkEqual(tabs.reopen(existing: [a, c]), nil, "a deleted note is not reopened")
    tabs = TabList(ids: [a, b], active: a, pinned: [a])
    tabs.close(a)
    tabs.reopen(existing: [a, b])
    check(tabs.isPinned(a) && tabs.ids == [a, b], "a reopened pinned tab is pinned again")
    tabs.activate(at: 1)
    checkEqual(tabs.active, b, "activate by position")
}
